#pragma once

// From glfw3.h
#define ATLAS_MOUSE_BUTTON_1         0
#define ATLAS_MOUSE_BUTTON_2         1
#define ATLAS_MOUSE_BUTTON_3         2
#define ATLAS_MOUSE_BUTTON_4         3
#define ATLAS_MOUSE_BUTTON_5         4
#define ATLAS_MOUSE_BUTTON_6         5
#define ATLAS_MOUSE_BUTTON_7         6
#define ATLAS_MOUSE_BUTTON_8         7
#define ATLAS_MOUSE_BUTTON_LAST      ATLAS_MOUSE_BUTTON_8
#define ATLAS_MOUSE_BUTTON_LEFT      ATLAS_MOUSE_BUTTON_1
#define ATLAS_MOUSE_BUTTON_RIGHT     ATLAS_MOUSE_BUTTON_2
#define ATLAS_MOUSE_BUTTON_MIDDLE    ATLAS_MOUSE_BUTTON_3